#빌드 스테이지
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .

# ARG 선언 & ENV 설정 추가
ARG VITE_SPRING_API_BASE_URL
ARG VITE_CHATBOT_API_BASE_URL
ARG VITE_TOSS_API_CLIENT_KEY
ARG VITE_NAVER_LOGIN_API_URL
ARG VITE_KAKAO_REDIRECT_URI
ARG VITE_KAKAO_CLIENT_ID

ENV VITE_SPRING_API_BASE_URL=$VITE_SPRING_API_BASE_URL
ENV VITE_CHATBOT_API_BASE_URL=$VITE_CHATBOT_API_BASE_URL
ENV VITE_TOSS_API_CLIENT_KEY=$VITE_TOSS_API_CLIENT_KEY
ENV VITE_NAVER_LOGIN_API_URL=$VITE_NAVER_LOGIN_API_URL
ENV VITE_KAKAO_REDIRECT_URI=$VITE_KAKAO_REDIRECT_URI
ENV VITE_KAKAO_CLIENT_ID=$VITE_KAKAO_CLIENT_ID

RUN npm run build

#실행 스테이지
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
EXPOSE 8080
EXPOSE 8000
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]