pipeline {
   agent any

   options {
       buildDiscarder(logRotator(numToKeepStr: '5'))
   }

   environment {
       ECR_REGISTRY = "${ECR_REGISTRY}"
       IMAGE_NAME = "my-project-spring"
       AWS_REGION = "ap-northeast-2"
       IMAGE_TAG = "${env.BUILD_NUMBER}"
   }


   stages {
       stage('Checkout') {
           steps {
               git branch: 'development', credentialsId: 'github-token',
                   url: 'https://github.com/novolunteer/final_spring.git'
           }
       }


       stage('Build') {
           steps {
               sh './gradlew clean build -x test'
           }
       }


       stage('Docker Build & Push') {
           steps {
               withAWS(credentials: 'aws-credentials', region: "${AWS_REGION}") {
                   sh '''
                       aws ecr get-login-password --region $AWS_REGION | \
                       docker login --username AWS --password-stdin $ECR_REGISTRY


                       docker build -t $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
                       docker tag $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG $ECR_REGISTRY/$IMAGE_NAME:latest
                       docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
                       docker push $ECR_REGISTRY/$IMAGE_NAME:latest
                   '''
               }
           }
       }


       stage('Deploy') {
           steps {
               withAWS(credentials: 'aws-credentials', region: "${AWS_REGION}") {
                   sh '''
                       aws eks update-kubeconfig --region ap-northeast-2 --name my-cluster

                       kubectl set image deployment/spring \
                           spring=$ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

                       kubectl rollout status deployment/spring --timeout=300s
                   '''
               }
           }
       }
   }


   post {
       success {
           echo '✅ Spring 배포 성공!'
       }
       failure {
           echo '❌ Spring 배포 실패!'
       }
       always {
           sh 'docker image prune -f'
           cleanWs()
       }
   }
}



