pipeline {
    agent any


    environment {
        ECR_REGISTRY = "${ECR_REGISTRY}"
        IMAGE_NAME = "my-project-python"
        AWS_REGION = "ap-northeast-2"
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }


    stages {
        stage('Checkout') {
            steps {
                git branch: 'development', credentialsId: 'github-token',
                    url: 'https://github.com/novolunteer/final_python.git'
            }
        }


        stage('Docker Build & Push') {
            steps {
                withAWS(credentials: 'aws-credentials', region: "${AWS_REGION}") {
                    sh '''
                        aws ecr get-login-password --region $AWS_REGION | \
                        docker login --username AWS --password-stdin $ECR_REGISTRY


                        docker build -t $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
                        docker tag $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG $ECR_REGISTRY/$IMAGE_NAME:latest
                        docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
                        docker push $ECR_REGISTRY/$IMAGE_NAME:latest
                    '''
                }
            }
        }


        stage('Deploy') {
            steps {
                withAWS(credentials: 'aws-credentials', region: "${AWS_REGION}") {
                    sh '''
                        aws eks update-kubeconfig --region ap-northeast-2 --name my-cluster
                        kubectl rollout restart deployment python
                        kubectl rollout status deployment python
                    '''
                }
            }
        }
    }


    post {
        success {
            echo '✅ Python 배포 성공!'
        }
        failure {
            echo '❌ Python 배포 실패!'
        }
        always {
            sh 'docker image prune -f'
        }
    }
}



