cloud.aws.credentials.access-key=YOUR_AWS_ACCESS_KEY
cloud.aws.credentials.secret-key=YOUR_AWS_SECRET_KEY
cloud.aws.s3.bucket=YOUR_BUCKET_NAME

naver.client-secret=YOUR_NAVER_CLIENT_SECRET
kakao.client-secret=YOUR_KAKAO_CLIENT_SECRET

chatbot.internal.api-key=YOUR_INTERNAL_API_KEY

ai.schedule.url=YOUR_AI_SERVICE_URL