spring.application.name=final_project

#MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#JPA
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}

tosspayments.secret-key=${TOSS_SECRET_KEY}

#spring.config.import=application-secret.properties

server.forward-headers-strategy=framework

naver.client-id=${NAVER_CLIENT_ID}
naver.redirect-uri=https://www.xyzoffer.xyz/api/social/login/naver/callback
naver.login.uri=https://www.xyzoffer.xyz/social/login/naver
react.uri=https://www.xyzoffer.xyz
kakao.client-id=${KAKAO_CLIENT_ID}
kakao.login.uri=https://www.xyzoffer.xyz/social/login/kakao
kakao.redirect-uri=https://www.xyzoffer.xyz/api/social/login/kakao/callback

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}

spring.elasticsearch.uris=${ELASTICSEARCH_URL}

spring.session.store-type=redis
spring.session.redis.flush-mode=on-save

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always